### ISSUE TITLE
django 3.2 以上版本数据库设置 ImageField、FileField 抛出 SuspiciousFileOperation 错误

### ISSUE THREAD

**Issue by watsonhaw5566** [jukanntenn/django-tencentcos-storage#5]
![image](https://github.com/jukanntenn/django-tencentcos-storage/assets/4210367/fdeed0db-e06e-423f-9c44-359f2549075d)

找了一下发现是 django3.2 版本后不需要加 / 前缀的问题。但我目前还不知道如何修改源码。我没有安装 poetry
关于这个问题的讨论链接是这个 https://code.djangoproject.com/ticket/32718

**Comment by jukanntenn** [comment]
感谢报告这个问题，已在 v0.2.1 版本中修复。
